-- 숫자함수 ROUND, TRUNC
--ROUND() - 반올림
SELECT ROUND(45.923, 2), ROUND(45.923), ROUND(45.923, -1) FROM DUAL;

--TRUNC() - 절삭
SELECT TRUNC(45.923, 2), TRUNC(45.923), TRUNC(45.923, -1) FROM DUAL;

--ABS() - 절대값
SELECT ABS(-42) FROM DUAL;

--CEIL() - 올림, FLOOR() - 내림
SELECT CEIL(3.14), FLOOR(3.14) FROM DUAL;

--MOD() - 나머지 리턴
SELECT 10 / 3, MOD(10, 3) AS 나머지 FROM DUAL;



-- 날짜 함수 SYSDATE, SYSTIMESTAMP
SELECT SYSDATE, SYSTIMESTAMP FROM DUAL;

-- 날짜도 연산이 가능 (일수 기준)
SELECT FIRST_NAME, SYSDATE - HIRE_DATE FROM EMPLOYEES; -- 일
SELECT FIRST_NAME, (SYSDATE - HIRE_DATE) / 7 AS WEEK FROM EMPLOYEES; -- 주
SELECT FIRST_NAME, (SYSDATE - HIRE_DATE) / 365 AS WEEK FROM EMPLOYEES; -- 년

SELECT FIRST_NAME, TRUNC((SYSDATE - HIRE_DATE) / 7) AS WEEK FROM EMPLOYEES; -- 일수 절삭

-- 날짜에도 TRUNC, ROUND 함수의 적용 가능
SELECT SYSDATE, TRUNC(SYSDATE), ROUND(SYSDATE) FROM DUAL;
-- TRUNC(날짜, 포멧형식), ROUND(날짜 , 포멧형식)
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL; -- 년 기준으로 절삭
SELECT TRUNC(SYSDATE, 'MONTH') FROM DUAL; -- 월 기준으로 절삭
SELECT TRUNC(SYSDATE, 'DAY') FROM DUAL; -- 해당 주에 일요일로 절삭

SELECT ROUND(SYSDATE, 'YEAR') FROM DUAL;
SELECT ROUND(SYSDATE, 'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE, 'DAY') FROM DUAL;
