-- 트랜잭션 (작업의 논리적 단위)

-- 오토커밋 상태 확인
SHOW AUTOCOMMIT;
-- 오토커밋 온
SET AUTOCOMMIT ON;
-- 오토커밋 오프
SET AUTOCOMMIT OFF;

CREATE TABLE DEPTS AS (SELECT * FROM DEPARTMENTS WHERE 1 = 1);
DELETE DEPTS WHERE DEPARTMENT_ID = 10;
SAVEPOINT DELETE10; -- 세이브 포인트
DELETE FROM DEPTS WHERE DEPARTMENT_ID = 20;
SAVEPOINT DELETE20; -- 세이브 포인트
DELETE FROM DEPTS;

-- 세이브 위치로
ROLLBACK TO SAVEPOINT DELETE20;
SELECT * FROM DEPTS;

ROLLBACK TO SAVEPOINT DELETE10;
SELECT * FROM DEPTS;

ROLLBACK;
SELECT * FROM DEPTS;

-- COMMIT (DML문장을 사용)
COMMIT;

INSERT INTO DEPTS VALUES(300, 'TEST', NULL, 1800);
SELECT * FROM DEPTS;
