-- 제약조건
-- PRIMARY KEY (테이블의 고유키, 중복X, NULL허용X)
-- NOT NULL (NULL값을 허용하지 않음)
-- UNIQUE KEY (중복X, NULL허용)
-- FOREIGN KEY (참조하는 테이블의 PK를 저장해논 컬럼, 참조테이블의 PK가 없다면 등록X, NULL 허용)
-- CHECK (정의된 형식만 저장되도록 허용)

-- 도메인 무결성 - 테이블의 한칸(도메인) 값은 하나의 값으로 이루어져야 한다.
-- 개체 무결성 - PK에 대한 내용
-- 참조 무경성 - FK에 대한 내용

-- HR의 제약조건 확인
SELECT * FROM USER_CONSTRAINTS;

-- 열 레벨 제약조건
CREATE TABLE DEPT2(
    DEPT_NO NUMBER(5) CONSTRAINT DEPT2_DEFT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(20) CONSTRAINT DEPT2_NAME_NN NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, -- 아무것도 입력하지 않으면 기본값 지정
    DEPT_PHONE VARCHAR2(20) NOT NULL CONSTRAINT DEPT2_PHONE_UK UNIQUE,
    DEPT_GENDER CHAR(1) CONSTRAINT DEPT2_GENDER CHECK(DEFT_GENDER IN('M', 'Y')),
    DEPT_LOCA NUMBER(4) CONSTRAINT DEPT2_LOCA REFERENCES LOCATIONS (LOCATION_ID)
);

DROP TABLE DEPT2;

-- 열 레벨 제약조건에서는 CONSTRAINT생략가능 (이름지정 불가)
CREATE TABLE DEPT2(
    DEPT_NO NUMBER(5) PRIMARY KEY,
    DEPT_NAME VARCHAR2(20) NOT NULL,
    DEFT_DATE DATE DEFAULT SYSDATE, -- 아무것도 입력하지 않으면 기본값 지정
    DEFT_PHONE VARCHAR2(20) NOT NULL UNIQUE,
    DEFT_GENDER CHAR(1) CHECK(DEFT_GENDER IN('M', 'W')),
    DEFT_LOCA NUMBER(4) REFERENCES LOCATIONS (LOCATION_ID)
);

DROP TABLE DEPT2;

-- 테이블 레벨 제약조건
CREATE TABLE DEPT2(
    DEFT_NO NUMBER(5),
    DEFT_NAME VARCHAR(20) NOT NULL,
    DEFT_DATE DATE DEFAULT SYSDATE,
    DEFT_PHONE VARCHAR(20) NOT NULL,
    DEFT_GENDER CHAR(1),
    DEFT_LOCA NUMBER(4),
    -- 제약조건을 아래에 명시
    CONSTRAINT DEPT2_NO_PK PRIMARY KEY (DEFT_NO/*, DEFT_NAME*/), -- 기본키/슈퍼키
    CONSTRAINT DEPT2_PHONE_UK UNIQUE (DEFT_PHONE),
    CONSTRAINT DEPT2_GENDER_CK CHECK (DEFT_GENDER IN ('M', 'W')),
    CONSTRAINT DEPT2_LOCA_FK FOREIGN KEY (DEFT_LOCA) REFERENCES LOCATIONS (LOCATION_ID)
);

-------- 위배되는 행위
-- 개체 무결성
INSERT INTO DEPT2 (DEFT_NO, DEFT_NAME, DEFT_PHONE, DEFT_GENDER, DEFT_LOCA)
VALUES (NULL, 'TEST', '01011112222', 'Y', 1000);
-- 참조 무결성
INSERT INTO DEPT2 (DEFT_NO, DEFT_NAME, DEFT_PHONE, DEFT_GENDER, DEFT_LOCA)
VALUES (1, 'TEST', '01011112222', 'M', -10);

--------------------------------------------------------------------------------
-- 제약조건의 추가삭제 (변경은 불가능)
DROP TABLE DEPT2;

CREATE TABLE DEPT2(
    DEPT_NO NUMBER(5), -- PK
    DEPT_NAME VARCHAR2(20), -- NOT NULL
    DEFT_DATE DATE DEFAULT SYSDATE, -- 아무것도 입력하지 않으면 기본값 지정
    DEFT_PHONE VARCHAR2(20), -- UNIQUE
    DEFT_GENDER CHAR(1), -- CHECK
    DEFT_LOCA NUMBER(4) -- FK
);

-- PK추가
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_NO_PK PRIMARY KEY (DEPT_NO);
-- UNQIUE추가
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_PHONE_UK UNIQUE (DEFT_PHONE);
-- CHECK추가
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_GENDER_CK CHECK (DEFT_GENDER IN ('M', 'W'));
-- FK추가
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_LOCA_FK FOREIGN KEY (DEFT_LOCA) REFERENCES LOCATIONS (LOCATION_ID);
-- NOT NULL문 MODIFY구문으로 변경.
ALTER TABLE DEPT2 MODIFY (DEPT_NAME VARCHAR(20) NOT NULL);

-- 제약조건 삭제 (제약조건 이름으로)
ALTER TABLE DEPT2 DROP CONSTRAINT DEPT2_NO_PK;
ALTER TABLE DEPT2 DROP CONSTRAINT DEPT2_PHONE_UK;
ALTER TABLE DEPT2 DROP CONSTRAINT DEPT2_GENDER_CK;
ALTER TABLE DEPT2 DROP CONSTRAINT DEPT2_LOCA_FK;


--------------------------------------------------------------------------------
--문제1.
--다음과 같은 테이블을 생성하고 데이터를 insert 하세요 커밋
--조건) M_NAME 는 가변문자형 널값을 허용하지 않음
--조건) M_NUM 은 숫자형 , 이름 mem_memnum_pk primary key
--조건) REG_DATE 는 날짜형 , 널값을 허용하지 않음 , 이름 mem_regdate_uk ) UNIQUE 키
--조건) GENDER 가변문자형
--조건) LOCA 숫자형 , 이름 mem_loca_loc_locid_fk ) foreign key 참조 locations 테이블 location_id

--CREATE TABLE MEM (
--    M_NAME VARCHAR(20) NOT NULL,
--    M_NUM NUMBER(5) CONSTRAINT MEN_MEMNUM_PK PRIMARY KEY,
--    REG_DATE DATE DEFAULT SYSDATE NOT NULL CONSTRAINT MEM_REGDATE_UK UNIQUE,
--    GENDER VARCHAR(20),
--    LOCA NUMBER(5) CONSTRAINT MEM_LOCA_LOC_LOCID_FK REFERENCES LOCATIONS (LOCATION_ID)
--);

CREATE TABLE MEM(
    M_NAME VARCHAR(20) NOT NULL,
    M_NUM NUMBER(5),
    REG_DATE DATE DEFAULT SYSDATE,
    GENDER VARCHAR(20),
    LOCA NUMBER(5)
);
ALTER TABLE MEM ADD CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY (M_NUM);
ALTER TABLE MEM ADD CONSTRAINT MEM_REGDATE_UK UNIQUE (REG_DATE);
ALTER TABLE MEM ADD CONSTRAINT MEM_GENDER_CK CHECK(GENDER IN ('M', 'W');
ALTER TABLE MEM ADD CONSTRAINT MOM_LOCA_LOC_LOCID_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS (LOCATION_ID);

INSERT INTO MEM VALUES ('AAA', 1, '2018-07-01', 'M', 1800);
INSERT INTO MEM VALUES ('BBB', 2, '2018-07-02', 'F', 1900);
INSERT INTO MEM VALUES ('CCC', 3, '2018-07-03', 'M', 2000);
INSERT INTO MEM VALUES ('DDD', 4, SYSDATE, 'M', 2000);

SELECT * FROM MEM;

--문제2.
--MEM 테이블과 LOCATIONS 테이블을 INNER JOIN 하고 
--m_name , m_mum , street_address , location_id 컬럼만 조회
--m_num 기준으로 오름차순 조회
SELECT M_NAME,
       M_NUM,
       L.STREET_ADDRESS,
       L.LOCATION_ID
FROM MEM M
JOIN LOCATIONS L ON M.LOCA = L.LOCATION_ID
ORDER BY M_NUM;

COMMIT;

--------------------------------------------------------------------------------
SELECT * FROM EMP_DETAILS_VIEW;