-- 연습문제
--1. EMPLOYEES 테이블에서 201번 사원의 이름과 이메일주소를 출력하는 익명블록

DECLARE
    EMP_NAME VARCHAR2(50);
    EMP_EMAIL EMPLOYEES.EMAIL%TYPE;
BEGIN
    SELECT CONCAT(FIRST_NAME || ' ', LAST_NAME) NAME,
           EMAIL
    INTO EMP_NAME, EMP_EMAIL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 201;
    
    DBMS_OUTPUT.PUT_LINE(EMP_NAME);
    DBMS_OUTPUT.PUT_LINE(EMP_EMAIL);
END;

SELECT * FROM EMPLOYEES;

--2. EMPLOYEES테이블에서 사원번호가 가장 큰 사원을 찾은 뒤 (MAX)
-- 이 번호  +1번으로 EMPS테이블 INSERT하는 익명블록
CREATE TABLE EMPS AS (SELECT * FROM EMPLOYEES WHERE 1 = 2);

DECLARE
    EMPS_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN
    SELECT MAX(EMPLOYEE_ID)+1
    INTO EMPS_ID
    FROM EMPLOYEES;
    
    INSERT INTO EMPS 
    VALUES (EMPS_ID, 'AAA', 'BBB', 'CCC', '010.0000.0000', SYSDATE, 'DDD', 8000, NULL, 104, 60);
    
    COMMIT;
END;

SELECT * FROM EMPS;